### ISSUE TITLE
Add ligatures

### ISSUE THREAD

**Issue by ctwise** [IBM/type#77] opened 2017-11-12 21:52 UTC
There don't appear to be any ligatures in the mono font. Please add them.

**Comment by davelab6** [comment] 2017-11-12 22:12
Which character pairs do you propose be ligated? :)

**Comment by glebd** [comment] 2017-11-13 00:04
This looks like a duplicate of #63

**Comment by seejamescode** [comment] 2017-11-13 02:19
Hi @ctwise, thanks for the ask!

Like @glebd mentioned, this is a duplicate of #63. Please continue the conversation there if you have some recommendations.

**Closed by seejamescode** 2017-11-13 02:19 UTC
