### ISSUE TITLE
Alignments examples don’t match text

### ISSUE THREAD

**Issue by jgagne** [IBM/type#33] opened 2017-10-20 23:09 UTC
![alignnments-oops-text-mismatch](https://user-images.githubusercontent.com/5142085/31844822-423f7820-b5c9-11e7-9446-377d965e4680.png)

### Justified Copy

**Oops!**
Flush right is reserved for languages that read right to left but is hard to read in Western Latin languages.

### Flush Right Copy

**Oops!**
Justified copy can fit into IBM typography, but we recommend not using this approach as it is difficult to do well and requires strong typographic expertise.

Hat tip @johnmcvey

**Comment by briandrum** [comment] 2017-10-23 10:53
Duplicate of #12

**Comment by seejamescode** [comment] 2017-10-23 14:20
Not a duplicate. I am just excel at making the same mistake twice...

**Closed** 2017-10-23 16:27 UTC
